# 
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/e1/motion_lstm.pt"
policy_path: "policy/motion_lstm.pt"
xml_path: "model/e2/scene_terrain.xml"

# Total simulation time
simulation_duration: 600.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

# kps: [80, 80, 20, 100, 20, 20, 80, 80, 20, 100, 20, 20]
kps: [
      100, 80, 80, 100, 20, 20, 
      100, 80, 80, 100, 20, 20,
      100,
      20, 20, 20, 20,
      20, 20, 20, 20,
      ]
kds: [
      4, 2, 2, 4, 0.7, 0.7,
      4, 2, 2, 4, 0.7, 0.7,
      4,
      0.5, 0.5, 0.5, 0.5,
      0.5, 0.5, 0.5, 0.5,]

default_angles: [  
                  -0.10,  0.0,  0.0,  0.15, -0.0, 0.0, 
                  -0.10,  0.0,  0.0,  0.15, -0.0, 0.0,
                  0.0,
                  0.05,   0.1,  0.1,  1.3,
                  0.05,  -0.1, -0.1,  1.3,
                  ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 21
num_obs: 72
include_phase_in_obs: False  # 是否在观测中包含相位（sin_phase, cos_phase），如果为True，num_obs应该是74

cmd_init: [0., 0, 0]
# gamepad_type: betop #logitech
gamepad_type: logitech #logitech
